### ISSUE TITLE
Causal forests with binary outcomes

### ISSUE THREAD

**Issue by wilvancleve** [swager/grf#120]
I'm curious as to what your roadmap looks like for binary outcome variables?

**Comment by swager** [comment]
This would be nice to have. Rough two-class classification can be done using a regression forest with 0-1 outcomes, but of course that doesn't cover the multiclass case.

**Comment by jtibshirani** [comment]
We actually all the building blocks ready in C++, we just don't expose a classification forest through the R interface. Hopefully one of us is able to tackle this soon!

**Comment by wilvancleve** [comment]
That's awesome: I'm prepping for an analysis for causal inference in an observational medical dataset and would love to use your library for estimation of a treatment effect on a probability scale. I'll keep my eyes peeled!

**Comment by swager** [comment]
If what you want to do is to estimate heterogeneous treatment effects with binary outcomes + treatment assignments, you can just directly use the existing ``causal_forest()`` function.

Assuming unconfoundedness and using potential outcomes notation, the causal_forest function gives you estimates for ``tau(x) = E[Y(1) - Y(0) | X = x]``, which appears to be the object you want. The provided confidence intervals are also formally justified for binary Y as long as Y(w) isn't a deterministic function of X (i.e., there's still some randomness in the outcome Y given X and W).

As an aside -- there are often concerns about using regression-based methods for causal inference with binary outcomes, because regression might extrapolate its predictions out of the [0, 1] range; e.g., with binary outcomes, practitioners often use linear regression instead of logistic regression. However, with forests, this not a problem, because forests simply estimate treatment effects by local averaging, and so they don't do this type of problematic extrapolation. (At a high level can think of forests as a type of fancy adaptive subgroup analysis.)

Note: If you use orthogonalization (as is highly recommended), it's in principle possible to get treatment effect estimates outside the allowable range in small samples if the forest is poorly tuned; however, I've never seen this problem arise in practice yet. If you run into issues like this, please don't hesitate to ask

Note 2: The only material difference between classification and regression forests with binary outcomes is in how they do the splitting inside each tree. This is relevant both from a computational speed and finite sample accuracy point of view, but doesn't actually affect the conceptual justification of the method. In principle, it might be useful to design a special splitting rule that's optimized for the case where Y and W are both binary; however, we don't have such a project currently in the works.

**Comment by wilvancleve** [comment]
Thanks so much for the very thorough response!

I'm finding myself confused in trying to actually implement the analysis you've suggested, mainly because I'm not sure I understand what's being returned by the predict method.

I'm analyzing a dataset where the treatment in which I'm interested is PROP_INFUSION and the outcome is ANY_PONV (both binary). There are a number of other variables in the X matrix.

```
cf <- causal_forest(X=as.matrix(for_grm %>% select(-ANY_PONV)),
                    Y=for_grm$ANY_PONV,
                    W=for_grm$PROP_INFUSION)
```
The Y.hat property of the returned object looks like a vector of means (in my case, probabilities of the binary outcome).

```
$ Y.hat            : num [1:14260, 1] 0.1916 0.0664 0.0936 0.1773 0.1608
```

When I run an in-sample prediction, however:

```
g <- predict(cf)
```

I get a predictions vector that is decidedly not giving me probabilities:

```
$ predictions       : num [1:14260, 1] 25.99 11.59 1.01 -89.16 -21.47 ...
```

I'm sorry to use this feature request thread to try to troubleshoot this, but I feel that it might help others who are looking at a similar type of analysis. Where am I missing out on what's being returned by the predict method? Is predict returning tau (the ITE, or the difference for each individual observation if PROP_INFUSION is flipped?) if so, on what scale is it returning this difference?

**Comment by swager** [comment]
No worries at all about using github issues for this. I changed the title so it reflects the current topic better. Here, the ``predict()`` function call is intended to return treatment effect estimates; the ``Y.hat`` field is just the result of an intermediate computation that's stored in case it's needed again.

Could you provide a simple example with synthetic data that reproduces the issue? A few things that might be worth looking at:
- Are the treatments PROP_INFUSION very sparse (are they mostly 0 or mostly 1)?
- Is the treatment assignment highly predictive (i.e., is P[W|X = x] mostly close to 0 or 1)?
- Does using the option ``precompute.nuisance = FALSE`` change results?

**Comment by wilvancleve** [comment]
Apologies for the delay in constructing a sample dataset.

I've attached an Rdata dataset containing a dplyr tibble called analytic.

https://drive.google.com/a/uw.edu/uc?authuser=1&id=0B-K7DM8py3jUSlVVVkc1SF9YaW8&export=download

The outcome variable is ANY_PONV (1/0). There are 3 predictors other than the treatment : 1 is a percentage (range 0 to 1) and the others are numeric (range 0 - 4 and 0 - 6)

The treatment is PROP_INFUSION (1/0).

When I run the following code : 

`grf <- causal_forest(X=as.matrix(as.matrix(analytic %>% dplyr::select(-ANY_PONV,-PROP_INFUSION))),
                     Y=analytic$ANY_PONV,
                     W=analytic$PROP_INFUSION)`
`pred <- predict(grf)`
`hist(pred$predictions`

I get a vector that ranges from -0.45 to 0.58. Including other variables in the analysis changes the scale of the output considerably, but I'm clearly not generating probabilities here. What is predict.causal_forest returning?

Thanks for looking and letting me know where you think I'm going astray.

**Comment by susanathey** [comment]
causal_forest returns treatment effects, not predicted probabilities.  Were you hoping to get predicted probabilities for the treatment and control group separately?

**Comment by wilvancleve** [comment]
I think, in my initial dataset, I had a variable in X that was closely correlated with W, and that's what led me to see treatment effects that were far outside of the range I was expecting.

For binary outcomes, then, to confirm, predict.causal_forest returns the estimated change in probability of Y associated with treatment W?

**Comment by swager** [comment]
Yes that's right. The `predict` function returns an estimate for `E[Y(1) - Y(0) | X = x]`, which should be between -1 and 1 here (since Y is binary).

Thanks a lot for sharing the dataset. I went ahead a tried running a few forests on it; I put a script below for reference. It appears that there's enough data to detect a significant ATE (if you believe in the unconfoundedness assumption); however, detecting personalized treatment effects is more difficult given the sample.

```R
library(grf)
library(dplyr)
load("grf.RData")

X=as.matrix(as.matrix(analytic %>% dplyr::select(-ANY_PONV,-PROP_INFUSION)))
Y=analytic$ANY_PONV
W=analytic$PROP_INFUSION

forest = causal_forest(X, Y, W)

# Estimate the average treatment effect. We perhaps have a moderate negative effect.
ate.hat = estimate_average_effect(forest)
print(paste("95% CI for ATE:", round(ate.hat["estimate"], 3), "+/-", round(1.96 * ate.hat["std.err"], 3)))
# [1] "95% CI for ATE: -0.022 +/- 0.018"

# Get pointwise heterogeneous treatment effect
tau.hat = predict(forest, estimate.variance = TRUE)

# The Z.score measures significance of the heterogeneous treatment effect
# estimates. Under the null, we might expect the Z-scores to be roughly standard Gaussian.
Z.score = tau.hat$predictions / sqrt(tau.hat$variance.estimates)
hist(Z.score) # one visualization
plot(tau.hat$predictions, sqrt(tau.hat$variance.estimates)) # another visualization
abline(0, 1/1.96); abline(0, -1/1.96)

# It looks like the Z-scores have a noted left skew. It appears that we may have
# some individuals for whom tau is negative, but we don't really have evidence that
# there's anyone for whom tau is positive.

# Try a forest with more regularization to get sharper insights.
forest2 = causal_forest(X, Y, W, sample.fraction = 0.1, min.node.size = 10, num.trees = 5000)
tau.hat2 = predict(forest2, estimate.variance = TRUE)

# The two forests seem to rouhgly have consistent predictions, and
# the ones from the regularized one are less noisy, but also somewhat
# underdispersed. (If the excess variance of tau.hat over tau.hat2 were
# only due to noise, we'd expect the slope to be 1 in the OLS below; but
# instead it's 1.5.)
plot(tau.hat2$predictions, tau.hat$predictions); abline(0, 1)
summary(lm(tau.hat$predictions ~ tau.hat2$predictions))

# However, the signal-to-noise ratio is still rather low. Under
# the null, we'd expect ~95% of the data to be above the `cone';
# here, 90% of the data is above it.
plot(tau.hat2$predictions, sqrt(tau.hat2$variance.estimates))
abline(0, 1/1.96); abline(0, -1/1.96)

# As closing thoughts: This dataset appears to potentially have a mild
# negative ATE (of course, this conclusion hinges on unconfoundedness being
# plausible here), but there's perhaps not enough data to meaningfully detect
# heterogeneity (unless there's a clear a-priori scientific hypothesis we
# could test).

# Finally, this example of course highlights the need for a strong cross-validation
# toolkit for GRF... it's under development!
```

**Comment by wilvancleve** [comment]
Appreciate your time and explanations very much. Thanks again.
