### ISSUE TITLE
Using regression_forest with a single regressor

### ISSUE THREAD

**Issue by jcook29** [swager/grf#123]
Thank you for making this package available. This package is incredibly useful for some projects on which I'm working. 

I am running into trouble when I call regression_forest with a single regressor. For example,
```
n = 50; p = 1
X = matrix(rnorm(n*p), n, p)
Y = X * rnorm(n)
r.forest = regression_forest(X, Y)

r.forest
```
reports the error
```
Error in rowSums(split.freq) : 
  'x' must be an array of at least two dimensions
```

**Comment by swager** [comment]
It looks like there's a bug in the `print.grf` method. When we print a forest, we usually provide a summary of which variables the forest chose to split on; however, that function gets confused if there's only one variable. Thank you for finding this bug; we will fix it.

In the mean time, since only the `print.grf` function is broken, you can still do other things with the forest, like make predictions or look at its state:
```R
Y.hat = predict(r.forest)$predictions
plot(X, Y.hat)

names(r.forest)
r.forest[["num.trees"]]
```
Finally, just as a statistical aside, if you want to use a random forest with a 1-dimensional X, then it's particularly important to tune the sampling rate or the minimum node size. In higher dimensions, random split variable choice provides a type of implicit regularization, but that doesn't happen in 1d.

**Comment by jcook29** [comment]
Thank you. I didn't realize it was still possible to make predictions. And thank you for advice regarding using random forest with 1-dimensional X.
