### ISSUE TITLE
About ci.group.size

### ISSUE THREAD

**Issue by predt** [swager/grf#255]
Hello,
Should the value of ci.group.size  (e.g. using 10 instead of the default value 2) change the characteristics of the ensemble of trees (e.g. the importance of covariates)?
If I understand correctly, it should only affect the calculation of the standard errors. Is that correct?
Many thanks.

**Comment by swager** [comment]
Yes, that's correct. In principle, one could try to tune `ci.group.size` such as to reduce the number of trees we need for accurate confidence intervals.

Note that using a larger value of `ci.group.size` may ever-so-slightly degrade the predictive performance of the forest, because trees are grown in correlated groups of size `ci.group.size` and this correlation makes the ensemble stabilizing effect a little less strong.

**Comment by jtibshirani** [comment]
Closing this out -- please feel free to re-open if you have further questions or suggestions.
