### ISSUE TITLE
What does cluster option do?

### ISSUE THREAD

**Issue by cnUCL** [swager/grf#280]
I am working on a project where it makes sense to cluster standard errors by household. I wondered what the clusters option does in causal_forests and instrumental_forests? 
Supplying a vector of indices for each household seems to change the point estimates for B(x) as well as the variance estimates. 
I couldn't find any information in the GRF paper or the reference about the clustering option. 

Any help would be greatly appreciated - thanks very much in advance!

**Comment by swager** [comment]
When you specify clusters, all sampling and inference is done in a way that respects cluster boundaries. In particular:

- When drawing a subsample on which to grow a tree, either we take the whole cluster or none of it.
- All inference is cluster-robust in the usual sense (i.e., error terms are allowed to be correlated within cluster).
- The confidence intervals for the forest predictions are bootstrap-based (see the paper for details); if clusters are specified, then this bootstrap is again by cluster (i.e., the whole cluster is in or out).

Finally, when growing an individual tree, it's not clear what to do with a cluster of observations. For this reason, when growing a tree (and after choosing the set of clusters it can use), we first draw `samples_per_cluster` observations from each cluster, and then grow a tree on those (so that each cluster gets the same weight). Note that all observations in the clusters used by the tree are considered "in bag", even if they were not among the `samples_per_cluster` data points actually used to grow the tree.

**Comment by cnUCL** [comment]
Dear Stefan,
Thank you very much, it's great that the function has this option built in and I will be using it.
Thanks for your help!

**Comment by jtibshirani** [comment]
I'm going to close out this issue, as the question's been resolved. We plan to add a description of clustering to our 'GRF Algorithm Reference' to better document how clustering works.
